# Generated by Django 6.0.7 on 2026-07-23 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#6750A4', help_text='Enter a hexadecimal color code.', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hexadecimal color code, such as #6750A4.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Enter an emoji such as 💻, 🎵 or ⚽.', max_length=20, verbose_name='Icon'),
        ),
    ]
